### PR TITLE
Fix MaskBool initialization on SSE

### LINKED ISSUE #255: operator[] of Masks returning undefined values
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.4.1 | Linux | gcc 9.3 | any | any | x86

## Testcase
```cpp
#include <iostream>
#include <Vc/Vc>
int main() {
  Vc::float_v a{1};
  Vc::float_v b{2};
  auto r = a < b;
  if (r[0]) std::cout << "OK\n"; else std::cout << "NOK\n";
}
```
## Actual Results
with no flags, one gets OK
with -ffinite-math-only, one gets NOK
But the important point is that it's undefined behavior

## Expected Results
obviously OK

## Analysis of the problem
If we suppose that we are in an SIMD case (let's say SSE for example), r is actually a Mask. Its actual type a m128, that is 4 floats for SSE. When calling r[0], we should get a boolean matching the value of the first item of the mask.
The code behind the scene is line 247 and then 225 of https://github.com/VcDevel/Vc/blob/1.4/Vc/sse/mask.h, and in practice does an implicit conversion of the internal float hold by the mask into a bool.

The first part of the problem is that such a conversion is undefined for nan values (https://stackoverflow.com/questions/9158567/nan-to-bool-conversion-true-or-false). One may not care too much. Except for the fact that the comparison operators in SIMD fill the masks with very special values (see https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cmplt_ps&expand=1073 or https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_cmp_ps&expand=1073,744) : 0 or 0xfffffff for false and true respectively. Now 0xffffffff is -nan, so for every true result we fall exactly into the undefined conversion case

## possible solution

One could (should ?) check the sign of the mask when converting to bool, using std::signbit explicitely on line 225 of https://github.com/VcDevel/Vc/blob/1.4/Vc/sse/mask.h for the SSE case

### PR DESCRIPTION
**Pull request by amyspark**
Fixes VcDevel/Vc#255 by initializing the mask in the same way as AVX.

Includes a test that will assess the condition if Vc is compiled with `-DCMAKE_CXX_FLAGS=-ffinite-math-only`. (In all other cases it'll always return true, as explained by the reporter.)

### CODE REVIEW

File: Vc/sse/mask.h [hunk 1]
```diff
@@ -222,7 +222,7 @@ template <typename T> class Mask<T, VectorAbi::Sse>
     friend reference;
     static Vc_INTRINSIC Vc_PURE value_type get(const Mask &m, int i) noexcept
     {
-        return MaskBool(m.d.m(i));
+        return m.toInt() & (1 << i);
```
Comment (bernhardmgruber) [inline Vc/sse/mask.h:225]: I guess that works. Looking at the previous implementation, it aliased the vector register by a T array and then accessed at `i`. That is what's happening in `m.d.m(i)`. So that might fore storing the register to memory. Your solution probably stays within the registers and might even be more efficient. AVX also uses your implementation.

**Review by bernhardmgruber — APPROVED** [review]

**Review by amadio — APPROVED** [review]
