### PR TITLE
Vector: add constructor taking an element reference

### LINKED ISSUE #256: Construct Vector from other Vector's reference
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
1.4   |      Linux?            |     GCC 10.2               |                |                     |

## Testcase
https://godbolt.org/z/bh9j9e

```c++
    Vc::float_v a;

    Vc::float_v works = (float)a[2];
    Vc::float_v fails = a[2]; // error: cannot convert Vc::float_v::reference to float
```

## Actual Results
Compilation failure

## Expected Results
Successful compilation. I think it should not be too hard to support creating a `Vc::Vector<T>` from another `Vc::Vector<T>::reference` and it would improve the usability quite a bit!

### PR DESCRIPTION
**Pull request by amyspark**
Hi again!

This MR fixes VcDevel/Vc#256. Tested with the following example under MSVC 19.29.30038.1:

```cpp
#include <Vc/Vc>
#include <iostream>

int main()
{
	Vc::float_v a;

	a[2] = 4.0f;

	Vc::float_v works = (float)a[2];
	Vc::float_v fails = a[2]; // error: cannot convert Vc::float_v::reference to float

	std::cout << works << fails << std::endl;

	return 0;
}
```

```
❯ .\build\Debug\main.exe
[4, 4, 4, 4][4, 4, 4, 4]
```

### CODE REVIEW

File: Vc/avx/vector.h [hunk 1]
```diff
@@ -159,6 +159,8 @@ template <typename T> class Vector<T, VectorAbi::Avx>
             explicit Vector(U &&x) Vc_INTRINSIC_R;
 #endif
 
+        Vc_INTRINSIC Vector(reference a) : Vector(static_cast<EntryType>(a)) {}
+
         ///////////////////////////////////////////////////////////////////////////////////////////
         // broadcast
         Vc_INTRINSIC Vector(EntryType a) : d(Detail::avx_broadcast(a)) {}
```
Comment (bernhardmgruber) [inline Vc/avx/vector.h]: From my gut feeling, I would have made this ctor `explicit`. But then `Vector(EntryType)` is also not explicit. So I guess I am fine with your solution.

**Review by bernhardmgruber — APPROVED** [review]
LGTM

I am still not sure however, if there could be any implications. Having this ctor seems so straight forward to me, that there might have been a reason to not include it. I would like to have a second opinion before merging this.

File: Vc/avx/vector.h (hunk 1 above)
Comment (amyspark) [reply Vc/avx/vector.h]: It seems your gut is right, not making it explicit introduces ambiguities across all constructors.

**Comment by agheata** [comment]
Shouldn't this come with a unit test before merging?

**Comment by bernhardmgruber** [comment]
> Shouldn't this come with a unit test before merging?

Absolutely right! @amyspark could you please add a small unit test as well? Something similar to the snippet you present here. Thank you!

**Comment by amyspark** [comment]
> 
> 
> > Shouldn't this come with a unit test before merging?
> 
> Absolutely right! @amyspark could you please add a small unit test as well? Something similar to the snippet you present here. Thank you!

Hey! I'm trying to find which unit test location fits this case, but I've not been able to yet.

File: tests/casts.cpp [hunk 2]
```diff
@@ -392,6 +392,17 @@ TEST(fullConversion)/*{{{*/
 }/*}}}*/
 #endif // Vc_DEFAULT_TYPES
 
+TEST(referenceConstruction)
+{
+    float_v a = float_v::Random();
+
+    Vc::float_v r = a[2];
```
Comment (bernhardmgruber) [inline tests/casts.cpp]: Your ctor is `explicit`, so you need:
```suggestion
    Vc::float_v r = Vc::float_v(a[2]);
```
or:
```suggestion
    Vc::float_v r(a[2]);
```

**Comment by amadio** [comment]
I agree with Bernhard that there may have been a reason not to include the constructor, e.g. to avoid enabling automatic conversions that are detrimental to performance and/or ambiguities about which constructor to use. However, if it is added as explicit, it is probably ok.

**Comment by amyspark** [comment]
I see only passes at http://cdash.cern.ch/index.php?project=Vc, anyone knows what's going on with CI?

**Comment by amadio** [comment]
We are looking into why the CI is showing the builds as failed. We should get this sorted out next week.

**Comment by amyspark** [comment]
@amadio any news as to CDash?

**Comment by amadio** [comment]
We think it's an issue with GitHub Actions itself. Nothing has changed on the CI configuration on our side. If GitHub Actions shows failures but we know from CDash that the builds actually passed, we can go ahead and merge the changes. I restarted the jobs to see if it will make any difference.

**Comment by amyspark** [comment]
It seems it's a known issue with CTest: https://gitlab.kitware.com/cmake/cmake/-/issues/20975

**Comment by amyspark** [comment]
I've pushed a commit that should resolve those two warnings that appear on CDash.

File: Vc/avx/const.h [hunk 3]
```diff
@@ -134,7 +134,7 @@ namespace AVX
     {
 #ifdef Vc_IMPL_AVX2
 #if defined Vc_ICC || defined Vc_MSVC
-        __m256i allone;
+        __m256i allone = __m256i();
         allone = _mm256_cmpeq_epi8(allone, allone);
```
Comment (amadio) [inline Vc/avx/const.h]: How about this?
```cpp
__m256i allone = _mm256_cmpeq_epi8(__m256i(), __m256i());
```

File: Vc/common/subscript.h [hunk 4]
```diff
@@ -233,7 +233,7 @@ struct IndexVectorSizeMatches<MinSize,
 
 template <std::size_t MinSize, typename T, std::ptrdiff_t N>
 struct IndexVectorSizeMatches<MinSize, Vc::Common::span<T, N>, false>
-    : public std::integral_constant<bool, (N == -1 || MinSize <= N)> {
+    : public std::integral_constant<bool, (N == -1 || MinSize <= static_cast<std::ptrdiff_t>(N))> {
```
Comment (amadio) [inline Vc/common/subscript.h]: Isn't `N` already of type `std::ptrdiff_t`? Why is the cast needed?

Comment (amyspark) [reply Vc/common/subscript.h]: I made a mistake here, the purpose of this is to resolve the C4018 on the comparison above.

**Comment by bernhardmgruber** [comment]
I think I have sorted out the CI issues: #297. You can rebase once the fix is merged.

**Comment by bernhardmgruber** [comment]
@amyspark please rebase on 1.4 again.

File: cmake/msvc_version.c [hunk 5]
```diff
@@ -0,0 +1 @@
+MSVC _MSC_FULL_VER
```
Comment (bernhardmgruber) [inline cmake/msvc_version.c]: I deleted this file in #290. Apparently, ctest still uses that to retrieve the exact MSVC version. However, this can also be done by just parsing the output of `cl.exe`. So here is a fix: #298. Please remove the commit that readds `msvc_version.c`. I really want that file to be gone :)

**Review by bernhardmgruber — CHANGES_REQUESTED** [review]

File: cmake/msvc_version.c (hunk 5 above)
Comment (amyspark) [reply cmake/msvc_version.c]: I'll bring your commit in!

File: Vc/avx/const.h [hunk 6]
```diff
@@ -119,8 +119,7 @@ namespace AVX
     {
 #ifdef Vc_IMPL_AVX2
 #if defined Vc_ICC || defined Vc_MSVC
-        __m256i allone;
-        allone = _mm256_cmpeq_epi8(allone, allone);
+        __m256i allone = _mm256_cmpeq_epi8(__m256i(), __m256i());
```
Comment (bernhardmgruber) [inline Vc/avx/const.h]: @amadio, how much worse is the codegen now? https://godbolt.org/z/E98Wrr7E7 A lot more instructions are produced now.

**Comment by bernhardmgruber** [comment]
@amyspark I think we might also need to add the new overload to `SimdArray`. Or at least add a unit test, that it also works with `SimdArray` please!

File: Vc/avx/const.h (hunk 6 above)
Comment (amadio) [reply Vc/avx/const.h:122]: Argh, compilers suck, let's go with this then: https://godbolt.org/z/s7qazEhd9
```cpp
return _mm256_xor_epi64(_mm256_setzero_si256(), _mm256_setzero_si256());
```

Comment (amadio) [reply Vc/avx/const.h]: Compilers suck, let's go with the `_mm256_set1_epi64x` call, but use `~0` instead of `-1`?

Comment (amyspark) [reply Vc/avx/const.h]: @bernhardmgruber, it looks like we ran into yet another case of https://developercommunity.visualstudio.com/t/Missed-optimization:-coalescing-contiguo/1471162 . But this one shows MSVC deoptimizes the whole function just by running into a register initialization? (Also, a small typo on your test case: the architecture flag in MSVC is `/arch`, you used the Clang/GCC version.)

@amadio complete test case here: https://godbolt.org/z/cbaGhPW4K. Any of the options (~0, -1, calling numeric_limits) will suffice.

File: Vc/avx/const.h [hunk 7]
```diff
@@ -119,8 +119,7 @@ namespace AVX
     {
 #ifdef Vc_IMPL_AVX2
 #if defined Vc_ICC || defined Vc_MSVC
-        __m256i allone;
-        allone = _mm256_cmpeq_epi8(allone, allone);
+        __m256i allone = _mm256_set1_epi64x(~0);
```
Comment (amadio) [inline Vc/avx/const.h:122]: Can we go with this for all compilers and remove the ifdefs? I think it should be optimal in all cases, no?

Comment (bernhardmgruber) [reply Vc/avx/const.h:122]: Depends. I read somewhere that sometimes generating the constant is faster than reading a value from static memory. So we would need to check the generated code whether `~0` is stored in the static data or computed. But then, you are the expert on such matter, so I take your recommendation ;)

Comment (amadio) [reply Vc/avx/const.h:122]: It's computed for the other compilers, and I think that's actually ok, because at most that takes a few cycles, so it's like loading from L1. Loading from memory can be fast, or not, depending on where you're loading from.

Comment (bernhardmgruber) [reply Vc/avx/const.h:122]: Let's use this implementation on all compilers now, but in a separate PR: #299.

**Review by bernhardmgruber — APPROVED** [review]
